"""web URL Configuration

The urlpatterns list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from music.views import (
    nav_page,
    login,
    admin_login,
    admin_page,
    admin_logout,
    api_get_music_data,
    api_get_music_detail,
    api_play_music,
    api_get_comment_data,
    api_get_comment_stats,
    index,
    get_random_image,
    music_hall,
    play_music,
    get_music_by_country,
    get_rank_data,
    get_rank_comments,
    music_recommendation,
    music_community,
    my_music,
    send_email_code,
    check_username_email,
    verify_email_code,
    register_user,
    check_find_password_username,
    send_find_password_email,
    verify_find_password_code,
    update_password,
    login_user,
    logout_user,
    get_remembered_username,
    get_creator_musics,
    user,
    save_profile,
    upload_avatar,
    delete_account,
    save_nickname,
    get_user_avatar,
    play_music_url,
    play_newsong_music_url,
    toggle_like,
    add_to_playlist,
    check_like_status,
    api_comment,
    api_comment_like,
    get_user_info,
    get_user_favorite_musics,
    get_music_info_by_id,
    api_music_search,
    api_get_rank_data,
    publish_community_record,
    get_community_records,
    delete_community_record,
    like_community_record,
    get_personalized_recommendations,
    apply_creator,
    publish_music,
    creator_centered,
    update_music_click_count,
    update_music_like_count,
    update_newsong_data,
    get_music_stats,
    api_get_users_list,
    api_delete_user,
    api_get_user_music_lib,
    api_delete_user_like_music,
    api_get_all_users_simple,
    api_get_creator_music_lib,
    api_audit_creator_music,
    api_get_creators_simple,
    api_recommend_by_markov,
    api_get_play_url_for_recommendation,
    api_proxy_music_stream,
    api_recommend_by_image,
    api_user_distribution_analysis,
    test_user_distribution_page,
    api_user_activity_analysis,
    api_music_popularity_analysis,
    api_rank_trend_analysis,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('nav/', nav_page, name='nav_page'),
    path('login/', login, name='login'),
    path('admin_login/', admin_login, name='admin_login'),
    path('admin_page/', admin_page, name='admin_page'),
    path('admin_logout/', admin_logout, name='admin_logout'),
    path('get_random_image/', get_random_image),
    path('index/', index, name='index'),
    path('music_hall/', music_hall, name='music_hall'),
    path('music_recommendation/', music_recommendation, name='music_recommendation'), 
    path('music_community/', music_community, name='music_community'),
    path('creator_centered/', creator_centered, name='creator_centered'),
    path('my_music/', my_music, name='my_music'),
    path('music/play/<str:music_id>/', play_music, name='play_music_stream'),
    path('get_music_by_country/', get_music_by_country, name='get_music_by_country'),
    path('get_rank_data/', get_rank_data, name='get_rank_data'),
    path('get_rank_comments/', get_rank_comments, name='get_rank_comments'),
    path('send_email_code/', send_email_code, name='send_email_code'),
    path('check_username_email/', check_username_email, name='check_username_email'),
    path('verify_email_code/', verify_email_code, name='verify_email_code'),
    path('register_user/', register_user, name='register_user'),
    path('check_find_password_username/', check_find_password_username, name='check_find_password_username'),
    path('send_find_password_email/', send_find_password_email, name='send_find_password_email'),
    path('verify_find_password_code/', verify_find_password_code, name='verify_find_password_code'),
    path('update_password/', update_password, name='update_password'),
    path('login_user/', login_user, name='login_user'),
    path('logout_user/', logout_user, name='logout_user'),
    path('get_remembered_username/', get_remembered_username, name='get_remembered_username'),
    path('user/<str:user_id>/', user, name='user'),
    path('save_profile/', save_profile, name='save_profile'),
    path('upload_avatar/', upload_avatar, name='upload_avatar'),
    path('delete_account/', delete_account, name='delete_account'),
    path('save_nickname/', save_nickname, name='save_nickname'),
    path('apply_creator/', apply_creator, name='apply_creator'),
    path('api/publish_music/', publish_music, name='publish_music'),
    path('avatar/<str:user_id>/', get_user_avatar, name='get_user_avatar'),
    path('music/play/', play_music, name='play_music'),
    path('play_music_url/', play_music_url, name='play_music_url'),
    path('play_newsong_music_url/', play_newsong_music_url, name='play_newsong_music_url'),
    path('music/toggle_like/', toggle_like, name='toggle_like'),
    path('music/check-like-status/', check_like_status, name='check_like_status'),
    path('api/add_to_playlist/', add_to_playlist, name='add_to_playlist'),
    path('api/comment/', api_comment, name='api_comment'),
    path('api/comment/like/<int:comment_id>/', api_comment_like, name='api_comment_like'),
    path('api/user/info/', get_user_info, name='get_user_info'),
    path('api/user/favorite_musics/', get_user_favorite_musics, name='get_user_favorite_musics'),
    path('api/music/info/', get_music_info_by_id, name='get_music_info_by_id'),
    path('api/music_hall/search/', api_music_search, name='api_music_search'),
    path('api/rank/<str:rank_type>/', api_get_rank_data, name='api_get_rank_data'),
    path('api/community/publish/', publish_community_record, name='publish_community_record'),
    path('api/community/records/', get_community_records, name='get_community_records'),
    path('api/admin/community/record/<int:record_id>/', delete_community_record, name='delete_community_record'),
    path('api/community/like/', like_community_record, name='like_community_record'),
    path('api/recommendations/', get_personalized_recommendations, name='get_personalized_recommendations'),
    # ★新增★：创作者功能 API
    path('api/creator/musics/', get_creator_musics, name='get_creator_musics'),
    path('api/music/click-count/', update_music_click_count, name='update_music_click_count'),
    path('api/music/like-count/', update_music_like_count, name='update_music_like_count'),
    path('api/music-stats/', get_music_stats, name='music_stats'),
    path('api/newsong/update-data/', update_newsong_data, name='update_newsong_data'),
    # ★管理后台 API★
    path('api/admin/music-data/', api_get_music_data, name='api_get_music_data'),
    path('api/admin/music-detail/', api_get_music_detail, name='api_get_music_detail'),
    path('api/admin/play-music/', api_play_music, name='api_play_music'),
    path('api/admin/comment-data/', api_get_comment_data, name='api_get_comment_data'),
    path('api/admin/comment-stats/', api_get_comment_stats, name='api_get_comment_stats'),
    path('api/admin/users-list/', api_get_users_list, name='api_get_users_list'),
    path('api/admin/delete-user/', api_delete_user, name='api_delete_user'),
    path('api/admin/user-music-lib/', api_get_user_music_lib, name='api_get_user_music_lib'),
    path('api/admin/delete-user-like-music/', api_delete_user_like_music, name='api_delete_user_like_music'),
    path('api/admin/all-users-simple/', api_get_all_users_simple, name='api_get_all_users_simple'),
    path('api/admin/creator-music-lib/', api_get_creator_music_lib, name='api_get_creator_music_lib'),
    path('api/admin/audit-creator-music/', api_audit_creator_music, name='api_audit_creator_music'),
    path('api/admin/creators-simple/', api_get_creators_simple, name='api_get_creators_simple'),
    # ★新增★：Markov 音乐推荐 API
    path('api/music/recommend-by-markov/', api_recommend_by_markov, name='api_recommend_by_markov'),
    # ★新增★：音乐播放链接（推荐专用）
    path('api-get-play-url-for-recommendation/', api_get_play_url_for_recommendation, name='api_get_play_url_for_recommendation'),
    # ★新增★：音乐流代理（解决 CORS 问题）
    path('api/proxy-music-stream/', api_proxy_music_stream, name='api_proxy_music_stream'),
    # ★新增★：图片识别推荐 API
    path('api/music/recommend-by-image/', api_recommend_by_image, name='api_recommend_by_image'),
    # ★新增★：用户分布分析 API
    path('api/admin/user-distribution/', api_user_distribution_analysis, name='api_user_distribution_analysis'),
    # ★新增★：用户分布分析测试页面
    path('test/user-distribution/', test_user_distribution_page, name='test_user_distribution_page'),
    # ★新增★：用户活跃度分析 API
    path('api/admin/user-activity/', api_user_activity_analysis, name='api_user_activity_analysis'),
    path('api/admin/music-popularity/', api_music_popularity_analysis, name='api_music_popularity_analysis'),
    path('api/admin/rank-trend/', api_rank_trend_analysis, name='api_rank_trend_analysis'),
]
